### ISSUE TITLE
CLI v1.0.2a Crashes on Empty (?) .sup Files

### ISSUE THREAD

**Issue by CarlEdman** [amichaelt/BDSup2SubPlusPlus#20]
Some source materials contains .sup files that are very small (~ 1 kByte).  I assume that these are empty, pro-forma subtitles.  Loading one of these in GUI mode results in the following log:

Loading foobar.sup
# > 1 (00:00:01.001)

PCS ofs:0x00000000, START, size:0x000b, comp#: 0, forced: false
PTS start: 00:00:01.001, screen size: 1920_1080
WDS ofs:0x00000018, size:0x000a, dim: 10_10
PDS ofs:0x0000002f, size:0x0007, ID: 0, update: 0, 1 entries
END ofs: 0x00000043
PCS ofs:0x00000050, NORM,  size: 0x000b, comp#: 0, forced: false, pal update: false
PTS: 00:00:01.043
WDS ofs:0x00000068, size:0x000a, dim: 10*10
END ofs: 0x0000007f
WARNING: missing PDS/ODS: last epoch is discarded

Detected 0 forced captions.

That is fine, but when loading the same .sup on the command line:

bdsup2sub++ --output "foobar.idx" "foobar.sup"

results in a crash.  That may not seem like a big issue, but it is somewhat of a pain when scripts automatically invoking bdsup2sub++ hang at this point.  It seems the proper behavior would be to output an empty result, rather than crashing.

**Comment by ghost** [comment]
Sorry, I hadn't noticed this before.  Can your provide such a sample file so I can look into it?

**Comment by CarlEdman** [comment]
Thanks for looking into this!  Here you are:  http://www.mediafire.com/file/72d7n3x37t1l2gr/foobar.sup

**Comment by ghost** [comment]
Hmm, can't seem to reproduce with the latest HEAD build.  It just says "Converting SUB/IDX" and finishes silently. Maybe the issue got indirectly fixed.  See if you can reproduce it yourself from the build here: https://www.dropbox.com/s/0m766wejvdi5n1g/bdsup2sub%2B%2B102b_20131303_Win32.7z

**Comment by CarlEdman** [comment]
Something between 1.0.2a and 1.0.2b must indeed have fixed it.  Same file produces crashes with 1.0.2a and works fine with 1.0.2b (as downloaded from your link).  I think this issue can be closed for real this time.
